/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moyskleytech.obsidian.material;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
